name: mako
channels:
  - conda-forge
dependencies:
  - python=3.4
  - click
  - sphinx
  - coverage
  - awscli
  - flake8
  - python-dotenv>=0.5.1
  - pandas
  - numpy
  - matplotlib
  - engarde
  - jupyter
  - ipython
  - pip:
    - sklearn-pandas
    - imbalanced-learn
