spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160101 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160201 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160301 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160401 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160501 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160601 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160701 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160801 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20160901 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20161001 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20161101 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20161201 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170101 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170201 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170301 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170401 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170501 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170601 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170701 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170801 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20170901 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20171001 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20171101 &
spark-submit --master yarn --deploy-mode cluster --num-executors 11 --py-files calculations.py,../schema_definition/schema.py general_statistics.py --day 20171201 &